baseURL: "https://pascalmichaillat.org/" 
title: Pascal Michaillat
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: pmichaillat

taxonomies:
    tag: tags

mediaTypes:
  text/tex:
    suffixes:
    - tex
  text/bib:
    suffixes:
    - bib  
  text/sty:
    suffixes:
    - sty
  text/bst:
    suffixes:
    - bst

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Design
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archive/
          weight: 5

params:
    description: "I am an Associate Professor of Economics at Brown University. I work on unemployment, economic slack, business cycles, macroeconomic policy, metascience."
    author: Pascal Michaillat
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pascal Michaillat
          subtitle: "I am an Associate Professor of Economics at Brown University. I work on unemployment, economic slack, business cycles, macroeconomic policy, and on science-related topics. In January–June 2023, I am visiting the Department of Economics at the University of California–San Diego."
          imageUrl: "/picture.jpeg"
          imageWidth: 140
          imageHeight: 140
          imageTitle: Pascal Michaillat
          buttons:
            - name: Papers
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Design
              url: /design/
    socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=cL23w-4AAAAJ"
    - name: Email
      url: "mailto:pascalmichaillat@brown.edu"
    - name: Office Hours
      url: /officehours/
    - name: Zoom
      url: "https://brown.zoom.us/my/pascalmichaillat"
    - name: Location
      url: /location/
    - name: GitHub
      url: "https://github.com/pmichaillat"
    - name: YouTube
      url: "https://www.youtube.com/@pmichaillat"
    - name: Substack
      url: "https://pmichaillat.substack.com"
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pascal Michaillat"
      icon: /favicon.ico
      iconHeight: 16

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 270
